name: Check for broken links

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  check-links:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run lychee link checker
        uses: lycheeverse/lychee-action@v1.0.7
        with:
          args: --verbose --no-progress --exclude-private --timeout 30s